import Layout from "@/components/layout";

import "@/styles/globals.scss";
import { Analytics } from "@vercel/analytics/react";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>Tomcy Thomas - React Developer & User Experience Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/tomc.png" />
      </Head>
      <Component {...pageProps} />
      <Analytics />
    </Layout>
  );
}
