import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Navbar from "@/components/navbar";
import HeroSection from "@/components/heroSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tomcy Thomas - React Developer & User Experience Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/tomc.png" />
      </Head>
      <main>
        <Navbar />
        <HeroSection />
      </main>
    </>
  );
}
